import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import Slider from '@/components/Slider'
import Categories from '@/components/Categories'
import Books from '@/components/Books'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <div className={styles.container}>
          <Slider />
          <section className={styles.booksSection}>
            <div className={styles.container}>
              <Categories />
              <Books />
            </div>
          </section>
        </div>
      </div>
    </>
  )
}
